version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir -p ~/.go_workspace/src/github.com/${CIRCLE_PROJECT_USERNAME}
      - run:
          name: ln
          command: ln -s ${HOME}/${CIRCLE_PROJECT_REPONAME} ${HOME}/.go_workspace/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
      - run:
          name: go get readline
          command: go get -d -v github.com/chzyer/readline
      - run:
          name: go get yaml
          command: go get -d -v gopkg.in/yaml.v2
      - run:
          name: go generate
          command: go generate -v ./...
      - run:
          name: go build
          command: go build -v
      - run:
          name: linter tests
          command: ./linter-tests.sh
      - run:
          name: flag tests
          command: ./flag-tests.sh
